# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(956, 596)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(956, 596))
        Form.setMaximumSize(QtCore.QSize(956, 596))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.fromcomboBox = QtWidgets.QComboBox(Form)
        self.fromcomboBox.setGeometry(QtCore.QRect(30, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.fromcomboBox.setFont(font)
        self.fromcomboBox.setObjectName("fromcomboBox")
        self.fromcomboBox.addItem("")
        self.tocomboBox = QtWidgets.QComboBox(Form)
        self.tocomboBox.setGeometry(QtCore.QRect(250, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.tocomboBox.setFont(font)
        self.tocomboBox.setObjectName("tocomboBox")
        self.tocomboBox.addItem("")
        self.calbutton = QtWidgets.QPushButton(Form)
        self.calbutton.setGeometry(QtCore.QRect(420, 150, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.calbutton.setFont(font)
        self.calbutton.setObjectName("calbutton")
        self.showtextBrowser = QtWidgets.QTextBrowser(Form)
        self.showtextBrowser.setGeometry(QtCore.QRect(50, 210, 441, 361))
        self.showtextBrowser.setStyleSheet("")
        self.showtextBrowser.setObjectName("showtextBrowser")
        self.clearButton = QtWidgets.QPushButton(Form)
        self.clearButton.setGeometry(QtCore.QRect(150, 150, 101, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(-2, -2, 960, 600))
        self.listView.setStyleSheet("background-image: url(:/2.jpg);")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(400, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
"color: rgb(74, 255, 240);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(400, 100, 121, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(74, 255, 240);\n"
"background-color: transparent;")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: transparent;\n"
"color: rgb(57, 197, 187);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.changeButton = QtWidgets.QPushButton(Form)
        self.changeButton.setGeometry(QtCore.QRect(170, 60, 61, 51))
        self.changeButton.setStyleSheet("image: url(:/arrow.png);\n"
"background-color: transparent;")
        self.changeButton.setText("")
        self.changeButton.setObjectName("changeButton")
        self.listView.raise_()
        self.fromcomboBox.raise_()
        self.tocomboBox.raise_()
        self.calbutton.raise_()
        self.showtextBrowser.raise_()
        self.clearButton.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.changeButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "exchange rate"))
        self.fromcomboBox.setItemText(0, _translate("Form", "请选择"))
        self.tocomboBox.setItemText(0, _translate("Form", "请选择"))
        self.calbutton.setText(_translate("Form", "计算"))
        self.showtextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.clearButton.setText(_translate("Form", "清空文本框"))
        self.label.setText(_translate("Form", "请输入货币量:"))
        self.label_2.setText(_translate("Form", "转换后货币种类"))
        self.label_3.setText(_translate("Form", "转换前货币种类"))
import picture_rc
