# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_decform(object):
    def setupUi(self, decform):
        decform.setObjectName("decform")
        decform.resize(688, 431)
        decform.setMinimumSize(QtCore.QSize(688, 431))
        decform.setMaximumSize(QtCore.QSize(688, 431))
        self.itemList = QtWidgets.QListWidget(decform)
        self.itemList.setGeometry(QtCore.QRect(0, 0, 451, 431))
        self.itemList.setStyleSheet("")
        self.itemList.setObjectName("itemList")
        self.addButton = QtWidgets.QPushButton(decform)
        self.addButton.setGeometry(QtCore.QRect(480, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(decform)
        self.deleteButton.setGeometry(QtCore.QRect(480, 130, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.detailsButton = QtWidgets.QPushButton(decform)
        self.detailsButton.setGeometry(QtCore.QRect(480, 230, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.detailsButton.setFont(font)
        self.detailsButton.setObjectName("detailsButton")
        self.editButton = QtWidgets.QPushButton(decform)
        self.editButton.setGeometry(QtCore.QRect(480, 330, 91, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.editButton.setFont(font)
        self.editButton.setObjectName("editButton")
        self.sumButton = QtWidgets.QPushButton(decform)
        self.sumButton.setGeometry(QtCore.QRect(610, 40, 51, 131))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.sumButton.setFont(font)
        self.sumButton.setObjectName("sumButton")
        self.sortButton = QtWidgets.QPushButton(decform)
        self.sortButton.setGeometry(QtCore.QRect(610, 230, 51, 141))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.sortButton.setFont(font)
        self.sortButton.setObjectName("sortButton")

        self.retranslateUi(decform)
        QtCore.QMetaObject.connectSlotsByName(decform)

    def retranslateUi(self, decform):
        _translate = QtCore.QCoreApplication.translate
        decform.setWindowTitle(_translate("decform", "收藏饰品列表"))
        self.addButton.setText(_translate("decform", "添加饰品"))
        self.deleteButton.setText(_translate("decform", "删除饰品"))
        self.detailsButton.setText(_translate("decform", "查看详情"))
        self.editButton.setText(_translate("decform", "修改饰品"))
        self.sumButton.setText(_translate("decform", "饰\n"
"品\n"
"统\n"
"计"))
        self.sortButton.setText(_translate("decform", "饰\n"
"品\n"
"排\n"
"序"))
