# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoDialog(object):
    def setupUi(self, InfoDialog):
        InfoDialog.setObjectName("InfoDialog")
        InfoDialog.resize(393, 302)
        InfoDialog.setMinimumSize(QtCore.QSize(393, 302))
        InfoDialog.setMaximumSize(QtCore.QSize(393, 302))
        self.curtypelabel = QtWidgets.QLabel(InfoDialog)
        self.curtypelabel.setGeometry(QtCore.QRect(50, 40, 301, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.curtypelabel.setFont(font)
        self.curtypelabel.setStyleSheet("")
        self.curtypelabel.setText("")
        self.curtypelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.curtypelabel.setObjectName("curtypelabel")
        self.getinlabel = QtWidgets.QLabel(InfoDialog)
        self.getinlabel.setGeometry(QtCore.QRect(50, 100, 301, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.getinlabel.setFont(font)
        self.getinlabel.setStyleSheet("")
        self.getinlabel.setText("")
        self.getinlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.getinlabel.setObjectName("getinlabel")
        self.selloutlabel = QtWidgets.QLabel(InfoDialog)
        self.selloutlabel.setGeometry(QtCore.QRect(50, 160, 301, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.selloutlabel.setFont(font)
        self.selloutlabel.setStyleSheet("")
        self.selloutlabel.setText("")
        self.selloutlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.selloutlabel.setObjectName("selloutlabel")
        self.ratiolabel = QtWidgets.QLabel(InfoDialog)
        self.ratiolabel.setGeometry(QtCore.QRect(50, 220, 301, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.ratiolabel.setFont(font)
        self.ratiolabel.setStyleSheet("")
        self.ratiolabel.setText("")
        self.ratiolabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ratiolabel.setObjectName("ratiolabel")

        self.retranslateUi(InfoDialog)
        QtCore.QMetaObject.connectSlotsByName(InfoDialog)

    def retranslateUi(self, InfoDialog):
        _translate = QtCore.QCoreApplication.translate
        InfoDialog.setWindowTitle(_translate("InfoDialog", "饰品详细信息"))
